version: '3'
services:
  backend:
    build: ./backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ../secrets:/app/secrets 
    env_file:
      - ./backend/.env  # バックエンド専用の .env ファイル
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      
 # - /app/node_modules 
    env_file:
      - ./frontend/.env  # フロントエンド専用の .env ファイル

